output:
  sort-results: true

linters:
  disable:
    - cyclop
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godox
    - goerr113
    - golint
    - gomnd
    - gosec
    - ifshort
    - interfacer
    - maintidx
    - maligned
    - nestif
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - varnamelen
    - wrapcheck
  enable-all: true